#!/usr/bin/env python3

import RPi.GPIO as GPIO
import time
import argparse
import subprocess


def main():
  parser = argparse.ArgumentParser(description='RPZ-PowerMGR shutdown request receiver')
  parser.add_argument('--gpio', type=int, default=16, help='GPIO# based on RPi.GPIO BCM')
  args = parser.parse_args()

  GPIO.setmode(GPIO.BCM)
  GPIO.setup(args.gpio, GPIO.IN)

  interval = 0.1

  while True:
    while True:
      if 1 == GPIO.input(args.gpio):
        break
      time.sleep(interval)

    while True:
      if 0 == GPIO.input(args.gpio):
        print('Detected GPIO{} H to L edge. Performs shutdown...'.format(args.gpio))
        subprocess.run(['poweroff'])
        break
      time.sleep(interval)


if __name__ == '__main__':
  main()
